<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Ludaryx.Application\Ludaryx.Application.csproj" />
    <ProjectReference Include="..\Ludaryx.Infrastructure\Ludaryx.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b23e6bf9-785d-4d3b-b98f-e2135eb1c5c7</UserSecretsId>
  </PropertyGroup>

</Project>
